### ISSUE TITLE
Erasing W25Q64 issue

### ISSUE THREAD

**Issue by mhaghighi** [Saanlima/Tools_src#2]
Hi,
I am able to successfully program a W25q64FV spi flash attached to my xc6slx9 FPGA using fpgaprog utility, but i have a strange problem while erasing it:

C:>fpgaprog.exe -v -b bscan_spi_lx9_qfp144.bit -f glue.bit -se -r
Using built-in device list
JTAG chainpos: 0 Device IDCODE = 0x24001093     Desc: XC6SLX9

Uploading "bscan_spi_lx9_qfp144.bit". DNA is 0x99d072ace141dcfe
Done.
Programming time 503.9 ms
Erasing External Flash Memory.
Found Winbond Flash (Pages=32768, Page Size=256 bytes, 67108864 bits).
Erasing    :
...........Failed Erasing Generic Flash.
Error occured.
USB transactions: Write 192 read 24 retries 0

Although the process fails, but after a power recycle (powering off and on again), the Done LED on the board won't turn-on which indicated that the flash content is deleted (at least partially).

One thing I suspect about is the BulkErase parameter in progalgspi.cpp which I had no idea about it and just copied it from previous parts.

**Comment by Saanlima** [comment]
If you specify erase-only (-se) then it will erase the whole chip.  The BulkErase parameter is the worst case erase time in seconds for a full chip erase.  I looked at the Winbond W25Q128FV data sheet and it states that a full chip erase might take up to 200 S so this parameter should be 200 for W25Q128FV (and probably some smaller value for the smaller parts based on their data sheet).

BTW, I never use full chip erase (-se) since it takes so long time for the big parts.  If you do -sa (erase, program & verify) then it will do partial erase (i.e. only erase the sectors that will be programmed by the bit file) which tends to be much quicker.

**Comment by mhaghighi** [comment]
Thank you,
Increasing the bulkerase parameter to 20 solved the problem partially! The flash is fully erased and verified within about 35s. The small problem still persist is the Done LED which remains ON untill performing a power cycle.

**Comment by mhaghighi** [comment]
I think I figured it out!
The DONE led remain ON because the FPGA is still configured by the bscan image. Seems that (-r) parameter does not work properly when used along with (-se), but works fine along with (-sa).

**Comment by Saanlima** [comment]
The data sheet for W25Q64 says that the full chip erase is typically 20 seconds but that it could take up to 100 seconds on some parts.  If you set bulkerase to 20 then it will be an error if it takes more than 20 seconds so you probably want to increase this to 100 to avoid timing out too soon on some parts.  There is no harm in setting it to 100 since it will only wait for the erase until the chip indicates that the erase has finished, i.e. if you have a fast part that will erase in 10 seconds then it will be done in 10 seconds and not wait the full 100 seconds.

As for the done LED, if you do -se then you only do an erase cycle **but no programming** even if you specify a bit file to program.  In this case it doesn't make sense to reload the bit file from flash since the flash is empty.

**Comment by mhaghighi** [comment]
You are right. I Updated BulkErase for W25Q64 and W25Q128 again and sent a pull request.
Thanks.
